
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  creationTimestamp: null
  name: resiliencies.dapr.io
  labels:
    app.kubernetes.io/part-of: "dapr"
spec:
  group: dapr.io
  names:
    kind: Resiliency
    listKind: ResiliencyList
    plural: resiliencies
    singular: resiliency
    categories:
    - dapr
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          scopes:
            items:
              type: string
            type: array
          spec:
            properties:
              policies:
                properties:
                  circuitBreakers:
                    additionalProperties:
                      properties:
                        interval:
                          type: string
                        maxRequests:
                          type: integer
                        timeout:
                          type: string
                        trip:
                          type: string
                      type: object
                    type: object
                  retries:
                    additionalProperties:
                      properties:
                        duration:
                          type: string
                        maxInterval:
                          type: string
                        maxRetries:
                          type: integer
                        policy:
                          type: string
                      type: object
                    type: object
                  timeouts:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              targets:
                properties:
                  actors:
                    additionalProperties:
                      properties:
                        circuitBreaker:
                          type: string
                        circuitBreakerCacheSize:
                          type: integer
                        circuitBreakerScope:
                          type: string
                        retry:
                          type: string
                        timeout:
                          type: string
                      type: object
                    type: object
                  apps:
                    additionalProperties:
                      properties:
                        circuitBreaker:
                          type: string
                        circuitBreakerCacheSize:
                          type: integer
                        retry:
                          type: string
                        timeout:
                          type: string
                      type: object
                    type: object
                  components:
                    additionalProperties:
                      properties:
                        inbound:
                          properties:
                            circuitBreaker:
                              type: string
                            retry:
                              type: string
                            timeout:
                              type: string
                          type: object
                        outbound:
                          properties:
                            circuitBreaker:
                              type: string
                            retry:
                              type: string
                            timeout:
                              type: string
                          type: object
                      type: object
                    type: object
                type: object
            required:
            - policies
            - targets
            type: object
        type: object
    served: true
    storage: true

