replicaCount: 1
logLevel: info
disableLeaderElection: true
image:
  name: dapr

nameOverride: ""
fullnameOverride: ""

runAsNonRoot: true

ports:
  protocol: TCP
  port: 80
  targetPort: 6500

resources: {}
