replicaCount: 1
logLevel: info
component: sidecar-injector

# Specify full docker image name including registry url to use the custom side car image
# Otherwise, helm chart will use {{ .Values.global.registry }}/daprd:{{ .Values.global.tag }}
image:
  name: ""

# Specify full docker image name including registry url to use a custom injector service image
# Otherwise, helm chart will use {{ .Values.global.registry }}/dapr:{{ .Values.global.tag }}
injectorImage:
  name: ""

nameOverride: ""
fullnameOverride: ""
webhookFailurePolicy: Ignore
sidecarImagePullPolicy: IfNotPresent
runAsNonRoot: true
sidecarRunAsNonRoot: true
sidecarReadOnlyRootFilesystem: true
resources: {}
kubeClusterDomain: cluster.local
ignoreEntrypointTolerations: "[{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"alibabacloud.com/eci\\\"},{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"azure.com/aci\\\"},{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"aws\\\"},{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"huawei.com/cci\\\"}]"
hostNetwork: false
healthzPort: 8080

livenessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 5

debug:
  enabled: false
  port: 40000
  initialDelaySeconds: 30000
