apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-subscriber
  labels:
    app: node-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-subscriber
  template:
    metadata:
      labels:
        app: node-subscriber
      annotations:
        actions.io/enabled: "true"
        actions.io/id: "node-subscriber"
        actions.io/port: "3000"
    spec:
      containers:
      - name: node-subscriber
        image: actionscore.azurecr.io/samples/node-subscriber
        ports:
        - containerPort: 3000
        imagePullPolicy: Always