name: Test Tooling

on:
  push:
    paths: # Explicitly declare which paths
      - ".github/workflows/test-tooling.yml"
      - ".build-tools/*"
  pull_request:
    branches:
      - master
    paths: # Explicitly declare which paths
      - ".github/workflows/test-tooling.yml"
      - ".build-tools/*"

permissions: {}

jobs:
  lint:
    name: Test (${{ matrix.os}})

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          # TODO: @joshvanl Upgrade to latest once dns is fixed.
          - "macos-14"
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    env:
      GOLANGCILINT_VER: "v1.64.6" # Make sure to bump /.build-tools/check-lint-version/main_test.go

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        # TODO: use actions/setup-go after https://github.com/actions/setup-go/pull/515 is merged and released
        uses: antontroshin/setup-go@461004e4c97225a313a997efabc35fde47d587bb
        with:
          go-version-file: './.build-tools/go.mod'


      - name: Tidy
        working-directory: ./.build-tools
        run: go mod tidy

      - name: Install Linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" ${{ env.GOLANGCILINT_VER }} 

      - name: Test
        working-directory: ./.build-tools
        run: go test ./...
